src/UsersBundle/Entity/UserCampaign.php
<?php

namespace UsersBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * UserCampaign
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="UsersBundle\Entity\Repositories\MyCampaignRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class UserCampaign
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="\AffiliateBundle\Entity\Users", inversedBy="camps")
     * @ORM\JoinColumn(name="user", referencedColumnName="id")
     */
    private $user;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="\AffiliateBundle\Entity\Campaigns", inversedBy="users")
     * @ORM\JoinColumn(name="campaign", referencedColumnName="id")
     */
    private $campaign;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="UserDomains", inversedBy="domains")
     * @ORM\JoinColumn(name="domain", referencedColumnName="id")
     */
    private $domain;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="\AffiliateBundle\Entity\Content", inversedBy="user_campaigns")
     * @ORM\JoinColumn(name="content", referencedColumnName="id")
     */
    private $content;

    /**
     * @var integer
     * @ORM\Column(name="unique_id", type="string", unique=true)
     */
    private $unique_id;

    /**
     * @var string
     * @ORM\Column(name="scriptCode", type="text")
     */
    private $scriptCode;

    /**
     * @var string
     * @ORM\Column(name="htmlCode", type="text")
     */
    private $htmlCode;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var string
     * @ORM\Column(name="campName", type="string")
     */
    private $campName;

    /**
     * @return string
     */
    public function getCampName()
    {
        return $this->campName;
    }

    /**
     * @param string $campName
     * @return $this
     */
    public function setCampName($campName)
    {
        $this->campName = $campName;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    /**
     * @param \DateTime $deletedAt
     * @return $this
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * @return string
     */
    public function getScriptCode()
    {
        return $this->scriptCode;
    }

    /**
     * @param $scriptCode string
     * @return $this
     */
    public function setScriptCode($scriptCode)
    {
        $this->scriptCode = $scriptCode;

        return $this;
    }

    /**
     * @return string
     */
    public function getHtmlCode()
    {
        return $this->htmlCode;
    }

    /**
     * @param string $htmlCode
     * @return $this
     */
    public function setHtmlCode($htmlCode)
    {
        $this->htmlCode = $htmlCode;

        return $this;
    }

    /**
     * @return int
     */
    public function getUniqueId()
    {
        return $this->unique_id;
    }

    /**
     * @param int $unique_id
     */
    public function setUniqueId($unique_id)
    {
        $this->unique_id = $unique_id;
    }

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set user
     *
     * @param integer $user
     *
     * @return UserCampaign
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return integer
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set campaign
     *
     * @param integer $campaign
     *
     * @return UserCampaign
     */
    public function setCampaign($campaign)
    {
        $this->campaign = $campaign;

        return $this;
    }

    /**
     * Get campaign
     *
     * @return integer
     */
    public function getCampaign()
    {
        return $this->campaign;
    }

    /**
     * Set domain
     *
     * @param integer $domain
     *
     * @return UserCampaign
     */
    public function setDomain($domain)
    {
        $this->domain = $domain;

        return $this;
    }

    /**
     * Get domain
     *
     * @return integer
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Set content
     *
     * @param integer $content
     *
     * @return UserCampaign
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return integer
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return UserCampaign
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }
}

src/UsersBundle/Resources/views/Dashboard/index.html.twig
{% extends "@Users/layout.html.twig" %}

{% block body %}

<div class="page-content">

    <!-- BEGIN PAGE HEADER-->
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="{{ path('admin_home') }}">{{ 'general.home'|trans({}, 'AppBundle') }}</a>
            </li>
        </ul>
    </div>
    <h3 class="page-title">
        {{ 'general.dashboard'|trans({}, 'AppBundle') }} <small>{{ 'general.report_stats' | trans({}, 'AppBundle') }}</small>
    </h3>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="dashboard-stat green-haze">
                <div class="visual">
                    <i class="fa fa-shopping-cart"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{ camps }}
                    </div>
                    <div class="desc">
                        {{ 'user_campaign.my_created_camps' | trans({}, 'AppBundle') }}
                    </div>
                </div>
                <a href="{{ path('my_camp_list') }}" class="more">{{ 'general.viewmore' | trans({}, 'AppBundle') }}</a>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="dashboard-stat blue-madison">
                <div class="visual">
                    <i class="fa fa-bar-chart-o"></i>
                </div>
                <div class="details">
                    <div class="number">
                        {{ activecamps }}
                    </div>
                    <div class="desc">
                        {{ 'user_campaign.active' | trans({}, 'AppBundle') }}
                    </div>
                </div>
                <a href="{{ path('my_camp_list') }}" class="more">{{ 'general.viewmore' | trans({}, 'AppBNundle') }}</a>
            </div>
        </div>
        </div>


        <div class="row">
            <div class="col-md-12">

                <div class="portlet">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bar-chart font-green-sharp hide"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">{{ 'general.last_month_stats'|trans({}, 'AppBundle') }}</span>
                            <span class="caption-helper">{{ 'general.click_view_stats'|trans({}, 'AppBundle') }}</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                            <td>{{ 'user_campaign.name'|trans({}, 'AppBundle') }}</td>
                            <td>{{ 'user_campaign.publish_site' | trans({}, 'AppBundle') }}</td>
                            <td>{{ 'content.type' | trans({}, 'AppBundle') }}</td>
                            <td>{{ 'general.total_click' | trans({}, 'AppBundle') }}</td>
                            <td>{{ 'general.total_view' | trans({}, 'AppBundle') }}</td>
                            </thead>
                            <tbody>
                            {% for stat in general_stats %}
                                {% set userCamp = stat[0].uniqueId|get_entity_row('UsersBundle:UserCampaign', 'unique_id', stat[0].uniqueId) %}
                                <tr>
                                    <td><a href="{{ path('reports_detail', { userCampaign: userCamp[0].id }) }}">{{ userCamp[0].campName }}</a></td>
                                    <td>{{ stat[0].siteId.name }}</td>
                                    <td>{{ userCamp[0].content.objectType }}</td>
                                    <td>{{ stat.totalClick }}</td>
                                    <td>{{ stat.totalView }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block javascripts %}


    <script src="{{ asset("bundles/users/assets/global/plugins/flot/jquery.flot.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/users/assets/global/plugins/flot/jquery.flot.resize.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/users/assets/global/plugins/flot/jquery.flot.categories.min.js") }}" type="text/javascript"></script>

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{ asset('bundles/users/assets/global/scripts/metronic.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bundles/users/assets/admin/layout/scripts/layout.js') }}" type="text/javascript"></script>
    <script src="{{ asset('bundles/users/assets/admin/layout/scripts/quick-sidebar.js') }}" type="text/javascript"></script>

    <!-- END PAGE LEVEL SCRIPTS -->

    <script>
        jQuery(document).ready(function() {
            Metronic.init(); // init metronic core componets
            Layout.init(); // init layout
            QuickSidebar.init(); // init quick sidebar
            Index.initCharts(); // init index page's custom scripts
        });

    </script>
{% endblock %}