src/UsersBundle/Form/RegistrationType.php
<?php
namespace UsersBundle\Form;

use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use UsersBundle\Form\DataTransformer\DomainTransformer;
use AffiliateBundle\Entity\Users;

class RegistrationType extends AbstractType
{

    private $entityManager;
    private $user;

    public  function  __construct(EntityManager $entityManager, Users $user) {
        $this->entityManager = $entityManager;
        $this->user = $user;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tc', 'text', array('attr' => array('class' => 'form-control'), 'required' => false, 'label' => 'user_register.tc', 'translation_domain' => 'UsersBundle'))
            ->add('taxNo', 'text', array('attr' => array('class' => 'form-control'), 'required' => false, 'label' => 'user_register.taxno', 'translation_domain' => 'UsersBundle'))
            ->add('taxAdmin', 'text', array('attr' => array('class' => 'form-control'), 'required' => false, 'label' => 'user_register.taxadmin', 'translation_domain' => 'UsersBundle'))
            ->add('fullName', 'text', array('attr' => array('class' => 'form-control'), 'label' => 'user_register.fullname', 'translation_domain' => 'UsersBundle'))
            ->add('phone', 'text', array('attr' => array('class' => 'form-control'), 'label' => 'user_register.phone', 'translation_domain' => 'UsersBundle'))
            ->add('email', 'email', array('attr' => array('class' => 'form-control'), 'label' => 'form.email', 'translation_domain' => 'FOSUserBundle'))
            ->add('plainPassword', 'repeated', array(
                'type' => 'password',
                'options' => array('translation_domain' => 'FOSUserBundle'),
                'first_options' => array('label' => 'form.password', 'attr' => array('class' => 'form-control')),
                'second_options' => array('label' => 'form.password_confirmation', 'attr' => array('class' => 'form-control')),
                'invalid_message' => 'fos_user.password.mismatch',
            ))
            ->add('country', 'country', array('attr' => array('class' => 'form-control', 'id' => 'countrySelect'), 'label' => 'user_register.country', 'translation_domain' => 'UsersBundle'))
            ->add('city', 'entity', array('attr' => array('class' => 'form-control'), 'class' => 'UsersBundle\Entity\Cities', 'label' => 'user_register.city', 'translation_domain' => 'UsersBundle'))
            ->add('address', 'textarea', array('attr' => array('class' => 'form-control'), 'label' => 'user_register.address', 'translation_domain' => 'UsersBundle'))
            ->add('domains', 'text', array('attr' => array('class' => 'form-control select2', 'id' => 'select2_sample1')))
        ;

        $builder->get('domains')->addModelTransformer(new DomainTransformer($this->entityManager, $this->user));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AffiliateBundle\Entity\Users',
            'intention'  => 'registration',
        ));
    }

    public function getParent()
    {
        return 'fos_user_registration';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getName()
    {
        return 'affiliate_user_registration';
    }
}

src/UsersBundle/Resources/views/MyCampaigns/campdetail.html.twig
{% extends "UsersBundle::layout.html.twig" %}

{% block title %}
    {{ 'campaign.detail'|trans({}, 'AppBundle') }}
{% endblock %}

{% block body %}

    <div class="page-content">

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{ path('all_camp_list') }}">{{ 'campaign.menu_name'|trans({}, 'AppBundle') }}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    {{ campaign.campName ~ ' ' ~ 'user_campaign.camp_detail'|trans({}, 'AppBundle') }}
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-list-ul"></i> {{ 'campaign.info' | trans({}, 'AppBundle') }}
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label bold">{{ 'campaign.name'|trans({}, 'AppBundle') }}</label> : <br/>
                                    {{ campaign.campName }}
                                </div>
                                <div class="form-group">
                                    <label class="control-label bold">{{ 'campaign.description'|trans({}, 'AppBundle') }}</label> : <br/>
                                    {{ campaign.description }}
                                </div>
                                <div class="form-group">
                                    <label class="control-label bold">{{ 'campaign.landing_url'|trans({}, 'AppBundle') }}</label> : <br/>
                                    <a target="_blank"  href="{{ campaign.landingUrl }}">{{ campaign.landingUrl }} <i class="fa fa-external-link"></i></a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label bold">{{ 'campaign.start_date'|trans({}, 'AppBundle') }}</label> : <br/>
                                    <div>
                                        {% if campaign.startDate is null %}
                                            <td></td>
                                        {% else %}
                                            <td>{{ campaign.startDate.format('Y-m-d H:i') }}</td>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label bold">{{ 'campaign.end_date'|trans({}, 'AppBundle') }}</label> : <br/>
                                    <div>
                                        {% if campaign.endDate is null %}
                                            <td></td>
                                        {% else %}
                                            <td>{{ campaign.endDate.format('Y-m-d H:i') }}</td>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-money"></i> {{ 'commission.list' | trans({}, 'AppBundle') }}
                        </div>
                    </div>
                    <div class="portlet-body">
                        {{ 'campaign.commissions'|trans({}, 'AppBundle') }}
                        <br><br>
                        {% for commission in commissions %}
                            <b>{{ commission.getComName() }} :</b>
                            <table class="table table-bordered table-responsive">
                                <thead>
                                    <th>{{ 'terms.name'|trans({}, 'AppBundle') }}</th>
                                    <th>{{ 'terms.term_op'|trans({}, 'AppBundle') }}</th>
                                    <th>{{ 'terms.values'|trans({}, 'AppBundle') }}</th>
                                </thead>
                                <tbody>
                                {% for term in terms %}
                                    <tr>
                                        <td>{{ term.termId }}</td>
                                        <td style="text-align: center">
                                            {% set arrTerm = term.termValues|json_decode %}
                                            {% if arrTerm.op_type is defined %}
                                                {% set termOp = arrTerm.op_type|get_entity_row('AffiliateBundle:TermsOps', 'id', arrTerm.op_type) %}
                                                {% if termOp|length > 0 %}
                                                    {{ termOp[0].value }}
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                        {% if term.termId.getTermType == 'country' %}
                                            <td>
                                                {% set values = term.termValues(true)|split(',') %}
                                                {% for country in values %}
                                                    {#
                                                        countryName'den sonra gelen if kısmını alt satıra koyunca arada 1 boşluk bırakıyordu.
                                                        Virgül ile ondan yanına taşıdım. String concate'de yapılabilir.
                                                    #}
                                                    {{ country|trim|countryName }}{% if not loop.last %},{% endif %}
                                                {% endfor %}
                                            </td>
                                        {% else %}
                                            <td>{{ term.termValues(true) }}</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-globe"></i>{{ 'content.list'|trans({}, 'AppBundle') }}
                        </div>

                    </div>
                    <div class="portlet-body">
                        {% for flashMessage in app.session.flashbag.get('campaigncontent_notice') %}
                            <div class="alert alert-success">
                                {{ flashMessage }}
                            </div>
                            <hr />
                        {% endfor %}


                        <h4>{{ 'campaign_content.related_contents'|trans({}, 'AppBundle') }}</h4>
                        <div class="row">
                        <div class="col-md-12">
                            {% for content in contents %}
                                {% if content.contentId.objectType == constant('AffiliateBundle\\Entity\\Content::TYPE_IMAGE') %}

                                    <div class="thumbnail campdetailimg">
                                        <div class="campdetailimgover">
                                        <img  src="{{ content.contentId.objectUrl }}" alt="{{ content.contentId.objectKey }}" style="display: block;" data-src="{{ content.contentId.objectUrl }}">
                                        </div>

                                    </div>

                                {%  endif %}
                            {% endfor %}
                            <div class="clearfix"></div>
                        </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/select2/select2.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-select/bootstrap-select.min.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/jquery-multi-select/css/multi-select.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css") }}"/>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/select2/select2.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-select/bootstrap-select.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js") }}"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/components-dropdowns.js") }}"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/jquery.pulsate.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/jquery-bootpag/jquery.bootpag.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/holder.js") }}" type="text/javascript"></script>

    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js") }}"></script>

    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/ui-general.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/ui-confirmations.js") }}"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/components-pickers.js") }}"></script>
    <script>
        jQuery(document).ready(function() {
            UIGeneral.init();
            ComponentsDropdowns.init();
            ComponentsPickers.init();
        });
    </script>
{% endblock %}

src/UsersBundle/Resources/views/MyCampaigns/camplist.html.twig
{% extends "UsersBundle::layout.html.twig" %}

{% block title %}
{{ 'campaign.list'|trans({}, 'AppBundle') }}
{% endblock %}

{% block body %}
<div class="page-content">



    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a>{{ 'campaign.menu_name'|trans({}, 'AppBundle') }}</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="{{ path('all_camp_list') }}">{{ 'campaign.list'|trans({}, 'AppBundle') }}</a>
            </li>
        </ul>
    </div>

    <h3 class="page-title">
        Destek Affiliate <small>{{ 'campaign.menu_name'|trans({}, 'AppBundle') }}</small>
    </h3>


    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box green-haze">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-globe"></i>{{ 'campaign.list'|trans({}, 'AppBundle') }}
                    </div>

                </div>
                <div class="portlet-body">
                    {% for flashMessage in app.session.flashbag.get('campaign_notice') %}
                    <div class="alert alert-success">
                        {{ flashMessage }}
                    </div>
                    {% endfor %}
                    <table class="table table-striped table-bordered table-hover" id="sample_6">
                        <thead>
                        <tr>
                            <th>{{ 'campaign.name'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'campaign.landing_url'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'campaign.description'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'campaign.start_date'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'campaign.end_date'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'general.detail'|trans({}, 'AppBundle') }}</th>
                            <th>{{ 'user_campaign.code_create'|trans({}, 'AppBundle') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for campaign in campaigns %}
                        <tr>
                            <td>{{ campaign.getCampName() }}</td>
                            <td>
                                <a  target="_blank"  href="{{ campaign.getLandingUrl() }}">

                                    {{ campaign.getLandingUrl() }}  <i class="fa fa-external-link"></i>
                                </a>
                            </td>
                            <td>{{ campaign.getDescription() }}</td>
                            {% if campaign.startDate is null %}
                                <td></td>
                            {% else %}
                                <td>{{ campaign.startDate.format('Y-m-d') }}</td>
                            {% endif %}

                            {% if campaign.endDate is null %}
                                <td></td>
                            {% else %}
                                <td>{{ campaign.endDate.format('Y-m-d') }}</td>
                            {% endif %}
                            <td><a href="{{ path('user_camp_detail', {'campaign': campaign.id}) }}"><i class="fa fa-cogs"></i></a></td>
                            <td style="text-align: center;"><a href="{{ path('user_camp_add', {'campaign': campaign.id}) }}"><i class="icon-plus"></i></a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>
{% endblock %}

src/UsersBundle/Resources/views/MyCampaigns/my_camp_detail.html.twig
{% extends "UsersBundle::layout.html.twig" %}

{% block title %}
    {{ 'campaign.detail'|trans({}, 'AppBundle') }}
{% endblock %}

{% block body %}

    <div class="page-content">

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="{{ path('user_home') }}">{{ 'general.home'|trans({}, 'AppBundle') }}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="{{ path('my_camp_list') }}">{{ 'user_campaign.created_codes'|trans({}, 'AppBundle') }}</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    {{ usercamp.campName }}
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-list-ul"></i> {{ 'user_campaign.created_camp_detail' | trans({}, 'AppBundle') }}
                        </div>
                    </div>
                    <div class="portlet-body form ">
                        <form method="post" action="{{ path('user_camp_my_camp_detail', {"userCampaign": usercamp.id}) }}">
                            <div class="campaingdetailform form-body">


                                        <div class="row">
                                        <div class="col-md-5 brdrlr ">




                                                <div class="form-group">
                                                    <label class="required">{{ form_label(form.campName) }}</label>
                                                    {{ form_widget(form.campName, {'attr': {'class': 'form-control'}}) }}
                                                    <span class="help-block"> {{ 'general.changeable'|trans({}, 'AppBundle') }} </span>
                                                </div>



                                                <div class="form-group">
                                                    <label class="required">{{ form_label(form.createdAt) }}</label>
                                                    {{ form_widget(form.createdAt, {'attr': {'class': 'form-control'}}) }}
                                                    <span class="help-block"> {{ 'general.unchangeable'|trans({}, 'AppBundle') }} </span>
                                                </div>


                                                <div class="form-group">
                                                    <label class="required">{{ form_label(form.scriptCode) }}</label>
                                                    <div style="clear:both"></div>
                                                    <textarea id="" cols="40" class="form-control" rows="3">{{ usercamp.scriptCode }}</textarea>
                                                    <span class="help-block"> {{ 'general.unchangeable'|trans({}, 'AppBundle') }} </span>
                                                </div>

                                                <div class="form-group">
                                                {{ form_row(form._token) }}
                                                <input type="submit" class="btn btn-success" value="{{ 'general.save' | trans({}, 'AppBundle') }}">
                                                </div>



                                            </div>
                                             <div class="col-md-4 ">
                                                <ul class="campainglistul">
                                                <li>
                                                    <label for="" class="required">{{ 'user_campaign.real_name' | trans({}, 'AppBundle') }}</label>
                                                    {{ usercamp.campaign.campName }}
                                                </li>

                                                <li>
                                                    <label for="" class="required">{{ 'user_campaign.real_desc' | trans({}, 'AppBundle') }}</label>
                                                    {{ usercamp.campaign.description }}
                                                </li>


                                                <li>
                                                   <label class="required">{{ 'user_campaign.camp_real_start_date' | trans({}, 'AppBundle') }}</label>
                                                    {% if usercamp.campaign.startDate is not null %}
                                                        {{ usercamp.campaign.startDate.format("Y-m-d H:i") }}
                                                    {% endif %}
                                                </li>

                                                <li >
                                                  <label class="required">{{ 'user_campaign.camp_real_end_date' | trans({}, 'AppBundle') }}</label>
                                                    {% if usercamp.campaign.endDate is not null %}
                                                        {{ usercamp.campaign.endDate.format("Y-m-d H:i") }}
                                                    {% else %}
                                                        {{ 'user_campaign.camp_no_end_date' | trans({}, 'AppBundle') }}
                                                    {% endif %}
                                                </li>


                                                <li >
                                                    <label for="" class="required">{{ 'user_campaign.selected_domain' | trans({}, 'AppBundle') }}</label>
                                                    <a href="{{ usercamp.domain.name }}">{{ usercamp.domain.name }}</a>
                                                </li>
                                                </ul>


                                            </div>



                                            <div class="col-md-3">
                                                <div class="form-group">
                                                <label class="control-label"><label for="" class="required">{{ 'user_campaign.selected_content' | trans({}, 'AppBundle') }}</label></label>
                                                <div id="htmlCode" style="width: 200px; height: 200px;"><script>{{ usercamp.htmlCode|raw }}</script></div>
                                                </div>
                                            </div>

                                         </div>




                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/select2/select2.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-select/bootstrap-select.min.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/jquery-multi-select/css/multi-select.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css") }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css") }}"/>
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/select2/select2.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-select/bootstrap-select.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js") }}"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/components-dropdowns.js") }}"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/jquery.pulsate.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/jquery-bootpag/jquery.bootpag.min.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/global/plugins/holder.js") }}" type="text/javascript"></script>

    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js") }}"></script>
    <script type="text/javascript" src="{{ asset("bundles/affiliate/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js") }}"></script>

    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/ui-general.js") }}" type="text/javascript"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/ui-confirmations.js") }}"></script>
    <script src="{{ asset("bundles/affiliate/assets/admin/pages/scripts/components-pickers.js") }}"></script>
    <script>
        jQuery(document).ready(function() {
            UIGeneral.init();
            ComponentsDropdowns.init();
            ComponentsPickers.init();

            $("#htmlCode *").attr("width", "100%").attr("height", "100%");
        });
    </script>
{% endblock %}